# Generated by Django 5.1.2 on 2024-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
